# Generated by Django 2.2 on 2019-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique_for_date='publish')),
                ('link', models.CharField(max_length=1000)),
                ('publish', models.DateTimeField()),
                ('info', models.TextField()),
            ],
        ),
    ]
