# Generated by Django 2.2 on 2019-04-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='publish',
            field=models.CharField(max_length=1000),
        ),
    ]
